name: the_fit_xone
description: "A fitness-focused mobile application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Typography
  google_fonts: ^6.1.0        # For Poppins/Inter fonts
  flutter_svg: ^2.0.9         # For SVG icons (future use)
  flutter_spinkit: ^5.2.1     # For the loading spinner in buttons

  # Core Utilities
  cupertino_icons: ^1.0.6
  # Youtube Videos
  youtube_player_flutter: ^9.0.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  provider: ^6.1.5+1
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  dartz: ^0.10.1
  equatable: ^2.0.7
  cloud_firestore: ^6.1.1
  http: ^1.2.0
  uuid: ^4.5.2
  intl: ^0.19.0
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Add the package dependency here
  flutter_launcher_icons: ^0.13.1

# Configuration for the icons (Must be at the root level, no indentation)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  # Optional: Background color for Android adaptive icons (Matches your AppColors.scaffoldBackground)
  adaptive_icon_background: "#1E1E2C"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # We will uncomment this later when you add actual images
  # assets:
  #   - assets/images/
  #   - assets/icons/